# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./front-react

    strategy:
      matrix:
        node-version: [18.x]
        
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        working-directory: ${{ env.working-directory }}
    - name: Install Dependencies
      run: npm install --force
      working-directory: ${{ env.working-directory }}
    - run: CI=false npm run build --if-present
      working-directory: ${{ env.working-directory }}
    - name: Deploy                  # S3에 배포하기
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.SECRET_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            /home/runner/work/wanted-pre-onboarding-frontend/wanted-pre-onboarding-frontend/front-react/build s3://select-task
